.TH CSS\-COLOR 1
.SH NAME
css\-color \- get css colors
.SH SYNOPSIS
.B css\-color
.R [COLOR OR NONE]
.SH DESCRIPTION
List all named css colors
.SH OPTIONS
.TP
.BR \-h ", "\-\-help
display help and exit
.TP
.BR \-r ", "\-\-random
Return a random color.
.TP
.BR \-s ", "\-\-shell
output in shell format
.TP
.BR \-f ", "\-\-full
show name, hex and rgb
