.TH IMDB\-QUOTE\-FETCHER 1
.SH NAME
imdb\-quote\-fetcher \- quotes from imdb
.SH SYNOPSIS
.B imdb\-quote\-fetcher
.R tt0113277
.SH DESCRIPTION
List all quotes from the provided imdb page
.SH OPTIONS
.TP
.BR \-h ", "\-\-help
display help and exit
.TP
.BR \-d ", "\-\-debug
Enable the Lisp debugger.
.TP
.BR \-D ", "\-\-no-debug
Disable the Lisp debugger (the default).
