.TH PIEK 1
.SH NAME
piek \- Send message to your iPhone
.SH SYNOPSIS
.B piek
.R [\-t TITLE \-m MESSAGE]
.SH DESCRIPTION
Notify your iPhone through hass
.SH OPTIONS
.TP
.BR \-h ", "\-\-help
display help and exit
.TP
.BR \-d " " \fIDEVICE\fR ", "\-\-device=\fIDEVICE\fR
say hello to NAME (default 50973046)
