.TH PIEK 1
.SH NAME
piek \- a cli remote for the tv
.SH SYNOPSIS
.B piek
.R [\-d DEVICE COMMAND]
.SH DESCRIPTION
.PP
Talk to the tv through the Harmony Hub using the API provided by Home Assistant.
.PP
I acknowledge the Rube Goldbergian aspect of this setup, but in return I can control my tv from my CLI, it's like a glimpse back to when software was not actively evil.
.PP
You can either talk directly to a device *piek \-d apple pause*, or switch to a specific harmony activity *piek \-a nintendo*
.PP
Needs the harmony.conf file from ssh://hass/config/harmony.conf when compiling
.PP
.SH OPTIONS
.TP
.BR \-h ", "\-\-help
display help and exit
.TP
.BR \-d " " \fIDEVICE\fR ", "\-\-device=\fIDEVICE\fR
send command to device(default lg)
.TP
.BR \-\-debug
Enable the Lisp debugger.
.TP
.BR \-\-no-debug
Disable the Lisp debugger (the default).
.TP
.BR \-a " " \fIACTIVITY\fR ", "\-\-activity=\fIACTIVITY\fR
switch to activity
.SH EXAMPLES
Volume Down TV':
.PP
.nf
.RS
piek -d lg volumedown
.RE
.fi
.PP
Pause Apple TV:
.PP
.nf
.RS
piek -d apple pause
.RE
.fi
.PP
Pause Telenet:
.PP
.nf
.RS
piek -d telenet pause
.RE
.fi
.PP
Show all commands of a device:
.PP
.nf
.RS
piek -d lg commands
.RE
.fi
