.TH RIP\-IT 1
.SH NAME
rip\-it \- print rip command
.SH SYNOPSIS
.B rip\-it
.R [OPTIONS] TITLE
.SH DESCRIPTION
bladiebla
.SH OPTIONS
.TP
.BR \-h ", "\-\-help
display help and exit
.TP
.BR \-m " " \fIMESSAGE\fR ", "\-\-message=\fIMESSAGE\fR
message
.TP
.BR \-l " " \fIMIN-LENGTH\fR ", "\-\-min-length=\fIMIN-LENGTH\fR
min\-length to keep, in minutes (default 50)
.TP
.BR \-r " " \fIREFERENCE\fR ", "\-\-reference=\fIREFERENCE\fR
imdb or tvdb ref
.TP
.BR \-d " " \fIDISC-NUMBER\fR ", "\-\-disc-number=\fIDISC-NUMBER\fR
specify disc number (default 0)
