#!/bin/zsh


bindkey -e # Emacs bindings

[[ $TERM == "dumb" ]] && unsetopt zle && PS1='$ ' && return

# Load [chruby](https://github.com/postmodern/chruby) and set default ruby
if [[ -d /usr/local/opt/chruby ]]
then
    source /usr/local/opt/chruby/share/chruby/chruby.sh
    source /usr/local/opt/chruby/share/chruby/auto.sh
else
    source /usr/local/share/chruby/chruby.sh
    source /usr/local/share/chruby/auto.sh
fi
chruby ruby-2.7

# Initializing autocomplete here, otherwise functions won't be loaded
# also load compdef so git-completion doesn't complain about no compdef
autoload -U compinit compdef
compinit
fpath=(/usr/local/share/zsh/site-functions/ $ZSH/functions $ZSH/completions $fpath)

# Use localrc for tokens and ignored stuff
if [[ -a $ZSH/zsh/localrc ]]
then
  source $ZSH/zsh/localrc
fi

config_files=($ZSH/zsh/*.zsh)

# load everything but the path and completion files
for file in ${${config_files}}
do
  source $file
done

# Use the [pure prompt](https://github.com/sindresorhus/pure)
#
# A pretty, minimal and fast ZSH prompt
autoload -U promptinit && promptinit
prompt pure
