#!/bin/zsh
bindkey -e # Emacs bindings

[[ $TERM == "dumb" ]] && unsetopt zle && PS1='$ ' && return

# Load [chruby](https://github.com/postmodern/chruby) and set default ruby
if [[ -d "${HOMEBREW_PREFIX:?}/share/chruby" ]]
then
    source "${HOMEBREW_PREFIX}/share/chruby/chruby.sh"
    source "${HOMEBREW_PREFIX}/share/chruby/auto.sh"
else
    source /usr/local/share/chruby/chruby.sh
    source /usr/local/share/chruby/auto.sh
fi
chruby ruby-2.7

# Initializing autocomplete here, otherwise functions won't be loaded
# also load compdef so git-completion doesn't complain about no compdef
autoload -U compinit compdef
compinit
fpath=(${HOMEBREW_PREFIX}/share/zsh/site-functions/ $ZSH/functions $ZSH/completions $fpath)

# Use localrc for tokens and ignored stuff
if [[ -a $ZSH/zsh/localrc ]]
then
  source $ZSH/zsh/localrc
fi

config_files=($ZSH/zsh/*.zsh)

# load everything but the path and completion files
for file in ${${config_files}}
do
  source $file
done

# Use the [pure prompt](https://github.com/sindresorhus/pure)
#
# A pretty, minimal and fast ZSH prompt
autoload -U promptinit && promptinit
prompt pure

if [[ -a ${HOMEBREW_PREFIX}/opt/asdf/asdf.sh ]]
then
  source /opt/homebrew/opt/asdf/asdf.sh
fi

# Try out [atuin](https://github.com/ellie/atuin)
eval "$(atuin init zsh)"
